services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    networks:
      - caddy
    volumes:
      - /plex/sonarr/config:/config
      - /plex/media/tv:/tv
      - /plex/media/downloads:/downloads
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    labels:
      caddy: tv.${DOMAIN}
      caddy.reverse_proxy: "{{upstreams 8989}}"

networks:
  caddy:
    external: true
